# Generated by Django 2.2.2 on 2022-07-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	dependencies = [
		('order', '0002_auto_20220723_2149'),
	]

	operations = [
		migrations.AlterField(
			model_name='order',
			name='car',
			field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING,
			                        related_name='order_car', to='cars.Car', verbose_name='下单关联的车辆'),
		),
	]
