# Generated by Django 2.2.2 on 2022-07-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=1, verbose_name='是否展示'),
        ),
    ]
