# Generated by Django 2.2.2 on 2022-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='user',
			name='real_user',
			field=models.BooleanField(default=0, verbose_name='是否实名'),
		),
	]
