# Generated by Django 2.2.2 on 2022-07-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_real_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.BooleanField(default=0, verbose_name='是否新用户'),
        ),
    ]
