# Generated by Django 2.2.2 on 2022-07-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Car',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('orders', models.IntegerField(verbose_name='优先级')),
				('name', models.CharField(max_length=128, verbose_name='车辆名称')),
				('car_type',
				 models.SmallIntegerField(choices=[(0, '轿车'), (1, 'SUV'), (2, '跑车')], default=0, verbose_name='车辆类型')),
				('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='价格')),
				('seats_choice',
				 models.SmallIntegerField(choices=[(2, '两座'), (5, '五座'), (7, '七座')], default=0, verbose_name='车座数')),
				('energy_type',
				 models.SmallIntegerField(choices=[(0, '新能源'), (1, '汽油')], default=0, verbose_name='能源类型')),
				('manual_trans',
				 models.SmallIntegerField(choices=[(0, '手动档'), (1, '自动挡')], default=0, verbose_name='变速箱')),
				('second_car',
				 models.SmallIntegerField(choices=[(0, '新车'), (1, '二手车')], default=0, verbose_name='是否二手')),
				('created_time', models.DateTimeField(auto_now_add=True, verbose_name='上市时间')),
				('stock_num', models.SmallIntegerField(default=5, verbose_name='车辆库存')),
			],
			options={
				'verbose_name': '汽车表',
				'verbose_name_plural': '汽车表',
				'db_table': 'cars',
			},
		),
		migrations.CreateModel(
			name='Car2Distributor',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('car',
				 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car', verbose_name='车辆')),
			],
			options={
				'verbose_name': '车辆与经销商中间表',
				'verbose_name_plural': '车辆与经销商中间表',
				'db_table': 'car2distributor',
			},
		),
		migrations.CreateModel(
			name='CarDetail',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('car_detail', models.TextField(max_length=1024, null=True, verbose_name='车辆描述')),
				('displacement', models.CharField(max_length=8, null=True, verbose_name='排量')),
				('color', models.CharField(max_length=8, verbose_name='车辆颜色')),
				('emission_standard',
				 models.SmallIntegerField(choices=[(0, '无'), (1, '国四'), (2, '国五'), (3, '国六'), (4, '国六b')], default=0,
				                          verbose_name='排放国标')),
				('mileage', models.CharField(max_length=16, verbose_name='车辆里程')),
				('production_mode',
				 models.SmallIntegerField(choices=[(0, '合资'), (1, '进口'), (2, '国产')], default=0, verbose_name='生产方式')),
				('trans_num', models.IntegerField(verbose_name='过户次数')),
				('popular', models.BigIntegerField(default=0, verbose_name='车辆人气')),
			],
			options={
				'verbose_name': '车辆详情表',
				'verbose_name_plural': '车辆详情表',
				'db_table': 'carDetail',
			},
		),
		migrations.CreateModel(
			name='CarFactory',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=64, verbose_name='厂商名称')),
				('addr', models.CharField(max_length=64, verbose_name='厂商地址')),
				('tel', models.BigIntegerField(verbose_name='联系方式')),
			],
			options={
				'verbose_name': '厂商表',
				'verbose_name_plural': '厂商表',
				'db_table': 'carFactory',
			},
		),
		migrations.CreateModel(
			name='Distributor',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=64, verbose_name='经销商名称')),
				('addr', models.CharField(max_length=64, verbose_name='经销商地址')),
				('tel', models.BigIntegerField(verbose_name='联系方式')),
				('cars', models.ManyToManyField(through='cars.Car2Distributor', to='cars.Car')),
			],
			options={
				'verbose_name': '经销商表',
				'verbose_name_plural': '经销商表',
				'db_table': 'distributor',
			},
		),
		migrations.CreateModel(
			name='CarsImg',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('img_url', models.CharField(max_length=256, verbose_name='车辆展示的图片链接后缀')),
				('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Car',
				                          verbose_name='图片所展示的车辆')),
			],
			options={
				'verbose_name': '车辆展示图片链接',
				'verbose_name_plural': '车辆展示图片链接',
				'db_table': 'cars_img',
			},
		),
		migrations.AddField(
			model_name='car2distributor',
			name='distributor',
			field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.Distributor',
			                        verbose_name='经销商'),
		),
		migrations.AddField(
			model_name='car',
			name='carFactory',
			field=models.ForeignKey(blank=True, db_constraint=False, null=True,
			                        on_delete=django.db.models.deletion.SET_NULL, to='cars.CarFactory',
			                        verbose_name='车厂'),
		),
		migrations.AddField(
			model_name='car',
			name='car_info_detail',
			field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.CarDetail'),
		),
		migrations.AddField(
			model_name='car',
			name='distributors',
			field=models.ManyToManyField(through='cars.Car2Distributor', to='cars.Distributor'),
		),
	]
