# Generated by Django 2.2.2 on 2022-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('cars', '0002_auto_20220723_1952'),
	]

	operations = [
		migrations.AlterField(
			model_name='car',
			name='orders',
			field=models.IntegerField(default=10, verbose_name='优先级'),
		),
	]
