# Generated by Django 2.2.2 on 2022-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPendingApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='车辆名称')),
                ('car_type', models.SmallIntegerField(choices=[(0, '轿车'), (1, 'SUV'), (2, '跑车')], default=0, verbose_name='车辆类型')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='价格')),
                ('seats_choice', models.SmallIntegerField(choices=[(2, '两座'), (5, '五座'), (7, '七座')], default=0, verbose_name='车座数')),
                ('energy_type', models.SmallIntegerField(choices=[(0, '新能源'), (1, '汽油')], default=0, verbose_name='能源类型')),
                ('manual_trans', models.SmallIntegerField(choices=[(0, '手动档'), (1, '自动挡')], default=0, verbose_name='变速箱')),
                ('second_car', models.SmallIntegerField(choices=[(0, '新车'), (1, '二手车')], default=1, verbose_name='是否二手')),
                ('carFactory', models.SmallIntegerField(verbose_name='厂家编号')),
                ('stock_num', models.IntegerField(default=1, verbose_name='库存数量')),
                ('is_approval', models.BooleanField(default=0, verbose_name='是否已审核')),
                ('car_info_detail', models.IntegerField(verbose_name='车辆详情id')),
                ('car_detail', models.TextField(max_length=1024, null=True, verbose_name='车辆描述')),
                ('displacement', models.CharField(max_length=8, null=True, verbose_name='排量')),
                ('color', models.CharField(max_length=8, verbose_name='车辆颜色')),
                ('emission_standard', models.SmallIntegerField(choices=[(0, '无'), (1, '国四'), (2, '国五'), (3, '国六'), (4, '国六b')], default=0, verbose_name='排放国标')),
                ('mileage', models.CharField(max_length=16, verbose_name='车辆里程')),
                ('production_mode', models.SmallIntegerField(choices=[(0, '合资'), (1, '进口'), (2, '国产')], default=0, verbose_name='生产方式')),
                ('trans_num', models.IntegerField(verbose_name='过户次数')),
                ('distributor_id', models.IntegerField(verbose_name='经销商id')),
                ('img_list', models.CharField(max_length=512, verbose_name='图片链接列表')),
            ],
            options={
                'verbose_name': '待审核车表',
                'verbose_name_plural': '待审核车表',
                'db_table': 'pending_approval_car',
            },
        ),
    ]
