# Generated by Django 2.2.2 on 2022-07-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpendingapproval',
            old_name='car_info_detail',
            new_name='car_detail_id',
        ),
        migrations.AlterField(
            model_name='carpendingapproval',
            name='trans_num',
            field=models.IntegerField(default=0, verbose_name='过户次数'),
        ),
    ]
