# Generated by Django 2.2.2 on 2022-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20220724_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpendingapproval',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格'),
        ),
    ]
