from ..serializers_user.login_serializer import MulLoginSerializer, MobileLoginSerializer, SellerLogin
from ..serializers_user.register_serializer import MobileRegisterSerializer, SellerMobileRegisterSerializer
from ..serializers_user.closer_account_serializer import CloseAccountSerializer
from ..serializers_user.dispaly_userinfo_serializer import DisplayUserInfoSerializer
from ..serializers_user.certification_serializer import CertificationSerializer


from ..serializers_user.dispaly_userinfo_serializer import UpdateUserIconSerializer
