# Generated by Django 2.2.2 on 2022-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_one', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='优惠券一')),
                ('coupon_two', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='优惠券二')),
                ('coupon_three', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='优惠券三')),
                ('new_user_coupon', models.DecimalField(decimal_places=2, default=0.8, max_digits=3, verbose_name='新用户优惠券')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
            ],
            options={
                'verbose_name': '优惠券表',
                'verbose_name_plural': '优惠券表',
                'db_table': 'auto_home_coupon',
            },
        ),
    ]
